### PR TITLE
Javascript filename cleanup

### PR DESCRIPTION
**Pull request by danielbitzer**
In an effort to cleanup the plugin's JS in general I've done an initial audit of the filenames.

## Deleted
- `facebook-settings.min.js` There is no un-minified version of this file and this file is not loaded anywhere within the plugin
- `facebook-for-woocommerce-products-admin.min.old.js` It's named "old" and isn't loaded anywhere
- `facebook-for-woocommerce-settings-messenger.js` This isn't loaded anywhere in the plugin

Feedback needed here since it's possible, however unlikely, that some 3rd party code in a different plugin is loading these JS files.

## Renamed

The name of the plugin is used inconsistently in the JS file names. I think it's best we remove all of these unnecessary references because it just makes it harder to quickly find files in the plugin.

- `facebook-for-woocommerce-product-sets-admin.js` to `product-sets-admin.js`
- `facebook-for-woocommerce-products-admin.js` to `products-admin.js`
- `facebook-for-woocommerce-settings-sync.js` to `settings-sync.js`
- `facebook-for-woocommerce-modal.js` to `modal.js`
- `facebook-metabox.js` to `metabox.js`
- `facebook-infobanner.js` to `infobanner.js`

## Inconsistent use of `admin/` directory

Some JS files were located in `/assets/js/admin` and some where located in `/assets/js`. However when looking closer at where these files are loaded they are _all_ loaded only in the admin area. Because of this I have moved all files into the `admin/` directory.

## Testing

Because these changes can broadly affect the UI I suppose we need to generally test that things are still working.

### CODE REVIEW

**Comment by danielbitzer** [comment]
Blocked as this might need significant updates after the 2.3.3 release branch is merged.

**Comment by haszari** [comment]
See comment on https://github.com/fbtransfer/facebook-for-woocommerce/pull/1826#issuecomment-807275023 – if we don't need to do this now to unblock specific fixes in 2.3.4, let's hold off until cooldown so we can do some solid testing. 

On the other hand, if we **do** need front end fixes for 2.3.4, let's discuss and come up with a plan for testing/QA for this and any other refactor / potentially major changes.

**Comment by budzanowski** [comment]
This is great. It will significantly improve working with the repository.

I have one request for the changes. Could you please check for the `SCRIPT_DEBUG` const and load un-minified .js files if that const is set to true?

**Comment by rcstr** [comment]
Updated base branch to `base-2.3.6`

**Comment by danielbitzer** [comment]
> Could you please check for the SCRIPT_DEBUG const and load un-minified .js files if that const is set to true?

I considered that but once we move to use webpack and `@wordpress/scripts` that won't be needed. I already have a PR for this https://github.com/woocommerce/facebook-for-woocommerce/pull/1826.

**Comment by haszari** [comment]
I see this branch (`setup-wp-scripts`) has been merged into #1826. Since all the changes are on that PR, and the changes are interrelated, I'm going to focus on #1826 - fix conflicts, test, review.

@danielbitzer Let me know your plan for these PRs - e.g. close this, focus on #1826; or merge separately; or merge one into the other (feature branch style). For now I'm assuming we'll focus on #1826.

**Comment by danielbitzer** [comment]
@haszari they are intended as separate PRs. #1826 is branching off this PR but I had to rebase this PR on to `master` due to some conflicts.

I will need to also rebase #1826.

**Comment by haszari** [comment]
As per #1826 - let's get this tidied up and ship in 2.5.0. Whatever testing is needed - let's make it happen! :shipit:

**Comment by haszari** [comment]
Removing `blocked` label - I don't think there's anything specific blocking this. Will need good testing but we can do that as part of 2.5.0 RC.

**Comment by danielbitzer** [comment]
@haszari do you mind reviewing/approving this PR? I've just merged and resolved conflicts with `master`. You would have already tested the changes when you approved #1826. And like you say we'll do more broader testing with the 2.5 RC.

**Review by haszari — APPROVED** [review]
Approving - based on testing / review of #1826 and 2.5.0 RC general testing 🚀 🛍️

**Pull request merged**
