### PR TITLE
Add filter to change retailer id in tracking snippet

### PR DESCRIPTION
**Pull request by miguelfspinto**
add option to change retailer id to match product id in custom product feeds

### CODE REVIEW

**Comment by miguelfspinto** [comment]
> Hi miguelfspinto! Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file.In order for us to review and merge your code, please sign at https://code.facebook.com/cla. **If you are contributing on behalf of someone else (eg your employer)**, the individual CLA may not be sufficient and your employer may need to sign the corporate CLA.
> 
> If you have received this in error or have any questions, please contact us at [cla@fb.com](mailto:cla@fb.com?subject=CLA%20for%20facebookincubator%2Ffacebook-for-woocommerce%20%231197). Thanks!

Already signed. Thank you.

**Comment by miguelfspinto** [comment]
Are you planning to deploy this change?

**Comment by miguelfspinto** [comment]
@ChaseWiseman , can you double check this issue and merge it? It seems a very easy and useful fix.

**Comment by miguelfspinto** [comment]
> @ChaseWiseman , can you double check this issue and merge it? It seems a very easy and useful fix.

@ChaseWiseman , do you have time to look at this?

**Comment by ChaseWiseman** [comment]
@miguelfspinto sorry for missing your first ping, my mistake!

I'll give this a look and see if it's something we can include in the next version. If so, I'll get it merged in to our ongoing base branch. 🍻

**Comment by miguelfspinto** [comment]
> @miguelfspinto sorry for missing your first ping, my mistake!
> 
> I'll give this a look and see if it's something we can include in the next version. If so, I'll get it merged in to our ongoing base branch. 🍻

@ChaseWiseman , thanks. :)
I also created a ticket in forum: https://wordpress.org/support/topic/problem-when-using-wpml-for-translated-products/

**Comment by abashinfection** [comment]
This would be a nice addition. 
Any chance this will be included in future releases?

**Comment by budzanowski** [comment]
This will be introduced using https://github.com/woocommerce/facebook-for-woocommerce/pull/2169. Closing.

**Pull request closed without merging**
