### PR TITLE
Fix coding standards with phpcbf and WooCommerce-core sniffs.

### PR DESCRIPTION
**Pull request by budzanowski**
Changes have been automatically generated using phpcbf and coding standards for WooCommerce.

### CODE REVIEW

**Comment by budzanowski** [comment]
The test is failing because it has found additional issues not fixable with phpcbf.

**Comment by Ismail-elkorchi** [comment]
The failing sniffs can be disabled individually in phpcs.xml to let the test pass. Then, in other PRs those disabled sniffs can be enabled as the errors related to it get fixed.

**Comment by budzanowski** [comment]
The plan is to live with the failing test for now but at the same time fix as many issues as possible until we don't have any.

**Comment by budzanowski** [comment]
Since this is auto-generated based on WooCommerce Core standard there is no reason, and sense ( given the size of the issue ) to review this. Merging.

**Comment by haszari** [comment]
Added to 2.5.0 - another reason to so some solid testing of the release (alongside autoloading #1919 and improving assets build #1826 #1824).

**Pull request merged**
