### PR TITLE
Migrating SkyVerge API and Exponential Backoff

### LINKED ISSUE #2095: Implement Exponential Backoff preventing issues caused by unavailable API services.
A recent Facebook services outage has uncovered an issue with the plugin. When the DNS records have not been available the plugin was blocking the site for some of the merchants. We need to implement a logic that will detect network issues and prevent the plugin from blocking the whole site.

The proposed solution is to use Truncated Exponential Backoff to stop plugins from doing requests when the responses are not coming through.

#### Refactor the code to get rid of SkyVerge dependency

[Refactor the code to get rid of SkyVerge dependency (1/10)](https://github.com/woocommerce/facebook-for-woocommerce/pull/2203#issuecomment-1123322488)

- [x] get_page - endpoint which returns Facebook page name and link information (also check if this endpoint is used anywhere).
- [x] get_product_group_product_ids - endpoint which returns an array of product id and retailer_id pairs.
- [x] next - endpoint used to call next results page of the previous request

[Refactor the code to get rid of SkyVerge dependency (2/10)](https://github.com/woocommerce/facebook-for-woocommerce/pull/2203#issuecomment-1123443828)

- [x] get_catalog

[Refactor the code to get rid of SkyVerge dependency (3/10)](https://github.com/woocommerce/facebook-for-woocommerce/pull/2203#issuecomment-1124888398)

- [x] get_user
- [x] delete_user_permission

[Refactor the code to get rid of SkyVerge dependency (4/10)](https://github.com/woocommerce/facebook-for-woocommerce/pull/2203#issuecomment-1125012043)

- [x] send_item_updates

[Refactor the code to get rid of SkyVerge dependency (5/10)](https://github.com/woocommerce/facebook-for-woocommerce/pull/2203#issuecomment-1126059196)

- [x] send_pixel_events

[Refactor the code to get rid of SkyVerge dependency (6/10)](https://github.com/woocommerce/facebook-for-woocommerce/pull/2214)

- [x] get_business_configuration
- [x] update_messenger_configuration
- [x] get_installation_ids
- [x] retrieve_page_access_token

Refactor the code to get rid of SkyVerge dependency (7/10)

- [ ] reanimate unit tests

Refactor the code to get rid of SkyVerge dependency (8/10)

- [ ] refactor `validate_product_catalog` and `is_product_catalog_valid` apis

Refactor the code to get rid of SkyVerge dependency (9/10)
Refactor the code to get rid of SkyVerge dependency (10/10)

- [ ] implement Truncated Exponential Backoff when calling Facebook API

#### Implement Exponential Backoff when talking to Facebook API

- [ ] implement exponential backoff on `perform_request` when calling to Facebook API

### PR DESCRIPTION
**Pull request by message-dimke**
### Changes proposed in this Pull Request:

Ref #2095 Implement Exponential Backoff preventing issues caused by unavailable API services.

Series of 10 PRs to migrate away from **SkyVerge API** into internal **WC_Facebookcommerce_Graph_API** and get rid of SkyVerge dependency.

### CODE REVIEW

**Comment by message-dimke** [comment]
## PR (1/10)

### Changes proposed in this Pull Request:

Removing `get_page`, `get_page_name` and `get_page_url` API methods as the ones not used. Migrating SkyVerge endpoint to retrieve product group product ids. Implementing `next` api method to enable pagination for multipage responses.

### Detailed test instructions:

1. Create new or reuse any existing Variable Product
2. If Product is not set to sync with Facebook - set it to do so, or, of Product is already synced - add a new variation and set it to sync with Facebook.

Edit_product_“V-Neck_T-Shirt_Category_Comma_Compatible”_‹_WordPress-Facebook_—_WordPress

3. Take a note of Product variants synced with Facebook by the time of this test.

Edit_product_“V-Neck_T-Shirt_Category_Comma_Compatible”_‹_WordPress-Facebook_—_WordPress

or if none

Edit_product_“Hoodie”_‹_WordPress-Facebook_—_WordPress

4. Hit Update Product button to save changes and sync the product.
5. Check new Product variation got its corresponding id 

Edit_product_“V-Neck_T-Shirt_Category_Comma_Compatible”_‹_WordPress-Facebook_—_WordPress

or, if were none

Edit_product_“Hoodie”_‹_WordPress-Facebook_—_WordPress

**Comment by message-dimke** [comment]
## PR (2/10)

### Changes proposed in this Pull Request:

Migrating SkyVerge `get_catalog` endpoint to retrieve catalog name for Facebook. Adjusting response parsing and `get_data` shortcut methods. Removing corresponding SkyVerge APIs.

### Detailed test instructions:

1. Connect/reconnect to Facebook or do nothing, since Facebook Catalog name is fetched on the fly w/o any caching or storing in the database.
2. See Facebook Catalog name is displayed

Facebook_for_WooCommerce_‹_WordPress-Facebook_—_WordPress

**Comment by message-dimke** [comment]
## PR (3/10)

### Changes proposed in this Pull Request:

Migrating SkyVerge `get_user` and `delete_user_permission` endpoints to disconnect from Facebook.

### Detailed test instructions:

1. Disconnect from Facebook.

Facebook_for_WooCommerce_‹_WordPress-Facebook_—_WordPress

2. Observe your store disconnected successfully.

**Comment by message-dimke** [comment]
## PR (4/10)

### Changes proposed in this Pull Request:

Migrating SkyVerge `send_item_updates` endpoints [Product Catalog Items Batch](https://developers.facebook.com/docs/marketing-api/reference/product-catalog/items_batch/).

### Detailed test instructions:

1. Go to Products > All Products and select product to update.

Products_‹_WordPress-Facebook_—_WordPress

2.  Pick Edit from bulk actions and hit Apply.
3. Update some property. e.g. `In Stock?` and hit Update button

Products_‹_WordPress-Facebook_—_WordPress

4. Go to WooCommerce Status page and open Logs tab

WooCommerce_status_‹_WordPress-Facebook_—_WordPress

WooCommerce_status_‹_WordPress-Facebook_—_WordPress

P.S. to see the logs, make sure to enable logging here

Facebook_for_WooCommerce_‹_WordPress-Facebook_—_WordPress

**Comment by message-dimke** [comment]
## PR (5/10)

### Changes proposed in this Pull Request:

Migrating SkyVerge `send_pixel_events`.

### Detailed test instructions:

1. Go to any product page.

Long_Sleeve_Tee_–_WordPress-Facebook

2. Open Facebook Events Manager.

Events_Manager

3. View Page Views.

Events_Manager

4. Open View Details and see recent events.

Events_Manager

5. Replay the same steps for View Content recent events.

Events_Manager

**Review by rawdreeg — APPROVED** [review]
These changes were previously tested and reviewed in #220.

Approving

**Pull request merged**
