### PR TITLE
Phpcs fixes in Facebook For WooCommerce.

### PR DESCRIPTION
**Pull request by budzanowski**
### Changes proposed in this Pull Request:

phpcs fixes for WooCommerce Core standard.

### How to test the changes in this Pull Request:

Plugin should work normally.

### Changelog entry
No changelog needed.

### CODE REVIEW

**Comment by haszari** [comment]
@budzanowski – Are these automated fixes (with `phpcbf`) or are some of these manual changes? Keen to get a better idea of the risk here and what needs code review.

**Comment by haszari** [comment]
Added to 2.6 for now, since we have a lot going on in 2.5. If these are all automated changes with `phpcbf` then maybe fine to include in 2.5.

**Comment by budzanowski** [comment]
@haszari no this is all manual.

**Comment by haszari** [comment]
This is getting stale, and since there's so much code impact I think it's risky - we need to do a lot of testing. I propose we close this and iterate on this one file at a time. I'm happy to add file exclusions to phpcs config and go slowly with this – there's no rush and we're a lean team. See also #1931

**Pull request closed without merging**
